### PR TITLE
Added install and data paths to xSPInstall

### PR DESCRIPTION
**Pull request by BrianFarnhill**
@anlynes @camiloborges @caadam @ykuijs - Code review for this one. No issue recorded but it's been asked for informally a couple of times. Just added options to the xSPInstall resource to allow customisation of the installation directories.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/266)

### CODE REVIEW

**Comment by camiloborges** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/xSharePoint/xSharePoint.xSPInstall.Tests.ps1, line 10 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/266#-KF1xXj0OmX48iIA0MXV:-KF1xXj0OmX48iIA0MXW:-285628494) ([raw file](https://github.com/powershell/xsharepoint/blob/55e3d47e245cf05fd37bfd231ebc681472f0e15d/Tests/xSharePoint/xSharePoint.xSPInstall.Tests.ps1#L10)):*
I know I am being a bit purist, perhaps pedantic , but shouldn't we have a test when you have the optional parameters and when you don't?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/266)*

**Comment by BrianFarnhill** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/xSharePoint/xSharePoint.xSPInstall.Tests.ps1, line 10 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/266#-KF1xXj0OmX48iIA0MXV:-KF2NZjcMgHp7cN6-0wM:676635175) ([raw file](https://github.com/powershell/xsharepoint/blob/55e3d47e245cf05fd37bfd231ebc681472f0e15d/Tests/xSharePoint/xSharePoint.xSPInstall.Tests.ps1#L10)):*
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/266)*

**Comment by camiloborges** [comment]
Reviewed 1 of 4 files at r1.
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/266)*

**Comment by camiloborges** [comment]
I tried to close the reviewable review. let me know if I screw it up again

**Comment by camiloborges** [comment]
Reviewed 1 of 4 files at r1.
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/266)*

**Comment by camiloborges** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/266)*

**Pull request merged**
