### PR TITLE
Added provisioning of proxy to xSPUsageApplication

### PR DESCRIPTION
**Pull request by BrianFarnhill**
@caadam @ykuijs @camiloborges @anlynes - Code review time, this is the fix for #247

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/254)

### CODE REVIEW

**Comment by camiloborges** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPUsageApplication/MSFT_xSPUsageApplication.psm1, line 44 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/254#-KEVXtc9rQNz1i_XSJrJ:-KEVXtc9rQNz1i_XSJrK:-2057651864) ([raw file](https://github.com/powershell/xsharepoint/blob/c2c9494c5442434a63a7e49f33380f2b7d3502b6/Modules/xSharePoint/DSCResources/MSFT_xSPUsageApplication/MSFT_xSPUsageApplication.psm1#L44)):*
I am not sure we should  use the $Ensure for that. Wouldn't it be better and easier if we had a $ProxyStatus parameter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/254)*

**Comment by BrianFarnhill** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPUsageApplication/MSFT_xSPUsageApplication.psm1, line 44 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/254#-KEVXtc9rQNz1i_XSJrJ:-KEYEw3Db9dk7Z4iz70H:1122689788) ([raw file](https://github.com/powershell/xsharepoint/blob/c2c9494c5442434a63a7e49f33380f2b7d3502b6/Modules/xSharePoint/DSCResources/MSFT_xSPUsageApplication/MSFT_xSPUsageApplication.psm1#L44)):*
No, the ensure parameter makes sense. If the proxy isn't there, then the service isn't fully provisioned, so it's not present. Adding another property to the schema that won't really be set doesn't make sense in the structure of a DSC resource. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/254)*

**Comment by camiloborges** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPUsageApplication/MSFT_xSPUsageApplication.psm1, line 44 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/254#-KEVXtc9rQNz1i_XSJrJ:-KEYLKJywonZjZZrtMtI:188504743) ([raw file](https://github.com/powershell/xsharepoint/blob/c2c9494c5442434a63a7e49f33380f2b7d3502b6/Modules/xSharePoint/DSCResources/MSFT_xSPUsageApplication/MSFT_xSPUsageApplication.psm1#L44)):*
Well, we are setting the Status in the Set  method by Provisioning it when Disabled. I am not too fussed about that, just wanted to make sure it won't confuse users. Merge it in :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/254)*

**Comment by camiloborges** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/254#-:-KEYUYLTpp68OtEBql_h:1417088721)*

**Comment by camiloborges** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/254)*

**Comment by caadam** [comment]
+1 Looks good. Sorry for the delay.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/254#-:-KEZGzeDXHKWeDbGWcvw:-1675990298)*

**Comment by caadam** [comment]
*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/254)*

**Pull request merged**
