### PR TITLE
Integrated core DscResource.Tests library

### LINKED ISSUE #275: Sharepoint is using an old version of DSCResource.Tests
Before submitting an issue to this project, please take a moment to provide the following details if possible:

- [x ] Is this a bug request or an enhancement request? no
- [N/A ] Version of PowerShell the DSC Target Node is running.
- [N/A ] Operating system the DSC Target Node is running.
- [X] Version of this DSC resource you're using. : https://github.com/PowerShell/xSharePoint/pull/272 
- [X] Details of the error that is occurring., none, tests are missing.
- [N/A ] The DSC configuration that is using the resource.

Thank you for contributing.
Your feedback and support is greatly appreciated.

If you are able to resolve this issue or add new features, you may submit a Pull Request against this project.
Please see the [Contribution Guideliness](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint) for information on how to contribute.

### PR DESCRIPTION
**Pull request by BrianFarnhill**
Fixes #275 - Have a look here @KarolKaczmarek and @TravisEz13 

- [X] Change details added to Unreleased section of readme.md?
- [N/A] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [N/A] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) run?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/278)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
@ykuijs @camiloborges @anlynes - can a brother get a code review?

**Comment by KarolKaczmarek** [comment]
I'll take a look at this tomorrow, but can you fix the PSSA failure?
```
3127There are PSScriptAnalyzer errors that need to be fixed:
 3128MSFT_xSPSecureStoreServiceApp.psm1 (Line 99): File 'MSFT_xSPSecureStoreServiceApp.psm1' uses ConvertTo-SecureString with plaintext. This will expose secure information. Encrypted standard strings should be used instead.
 3129For instructions on how to run PSScriptAnalyzer on your own machine, please go to https://github.com/powershell/psscriptAnalyzer/
```

**Comment by BrianFarnhill** [comment]
@KarolKaczmarek Yea I found a couple of tests that weren't executing that I patched up, you caught me midway through fixing it. I'll post here again when it's done, should be in time for you to review tomorrow

**Comment by BrianFarnhill** [comment]
@KarolKaczmarek Tests are green now, review away

**Comment by KarolKaczmarek** [comment]
*[appveyor.yml, line 8 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQNERXWjlQqGwsU2uj:-KFQNERXWjlQqGwsU2uk:1669197080) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/appveyor.yml#L8)):*
How about cloning it to $env:PPVEYOR_BUILD_FOLDER\Tests folder instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/278)*

**Comment by KarolKaczmarek** [comment]
*[appveyor.yml, line 28 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQXLCr8jDXVjjIuUPP:-KFQXLCr8jDXVjjIuUPQ:-927562856) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/appveyor.yml#L28)):*
I'm not 100% sure, but doesn't powershell load this module to memory at the time of first import?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/278)*

**Comment by KarolKaczmarek** [comment]
*[Tests/xSharePoint.TestHarness.psm1, line 19 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQYlaBpPyQN3uwztgb:-KFQYlaBpPyQN3uwztgc:1773700231) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/Tests/xSharePoint.TestHarness.psm1#L19)):*
Probably good idea to parametrize this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/278)*

**Comment by KarolKaczmarek** [comment]
*[Tests/xSharePoint.TestHarness.psm1, line 25 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQYqShecPSq81hztbE:-KFQYqShecPSq81hztbF:51479087) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/Tests/xSharePoint.TestHarness.psm1#L25)):*
same with versions here and the one below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/278)*

**Comment by KarolKaczmarek** [comment]
Review status: 0 of 100 files reviewed at latest revision, 5 unresolved discussions.

---

*[appveyor.yml, line 7 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQMcNY-nPRMEOr5QeF:-KFQMcNY-nPRMEOr5QeG:1183482662) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/appveyor.yml#L7)):*
Why are we removing it? At this point xDscesource.Tests isn't there so simple test should suffice and eventually we could remove it in the unlikely case it exists?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/278)*

**Comment by KarolKaczmarek** [comment]
Reviewed 36 of 99 files at r1, 1 of 2 files at r2, 2 of 63 files at r3, 61 of 62 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/278)*

**Comment by BrianFarnhill** [comment]
Review status: 99 of 100 files reviewed at latest revision, 5 unresolved discussions.

---

*[appveyor.yml, line 7 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQMcNY-nPRMEOr5QeF:-KFYDcycNQ0l6z7Y40hK:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/appveyor.yml#L7)):*
Done.

---

*[appveyor.yml, line 8 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQNERXWjlQqGwsU2uj:-KFYCQRr9LPXuRh8u-Sj:1325630086) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/appveyor.yml#L8)):*
It misses the DSC resource then because we separate the tests out from the main module, that way when we zip up and package the resource we don't ship the unit tests and other "stuff" along with it

---

*[appveyor.yml, line 28 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQXLCr8jDXVjjIuUPP:-KFYCqQPn4EhA7tRkVFn:1242442764) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/appveyor.yml#L28)):*
We move it to make sure it doesn't get included in the packaged build output, so we reload it from this location (and it goes to the first location as that is the only place that will pick up the modules due to the way that DscResource.Tests is written)

---

*[Tests/xSharePoint.TestHarness.psm1, line 19 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQYlaBpPyQN3uwztgb:-KFYDArHhNZrsRAjmzV5:21549960) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/Tests/xSharePoint.TestHarness.psm1#L19)):*
Parametise it how?

---

*[Tests/xSharePoint.TestHarness.psm1, line 25 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQYqShecPSq81hztbE:-KFYDCzeWq4V2d3tidr3:-1174315493) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/Tests/xSharePoint.TestHarness.psm1#L25)):*
Again - parametise it how?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/278)*

**Comment by BrianFarnhill** [comment]
Review status: 98 of 100 files reviewed at latest revision, 5 unresolved discussions.

---

*[Tests/xSharePoint.TestHarness.psm1, line 25 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQYqShecPSq81hztbE:-KFb8FQi70mnzn0ZF3YM:-1916758133) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/Tests/xSharePoint.TestHarness.psm1#L25)):*
I think this is what you meant with parameterising things, let me know if you think it needs something else when you see the latest cut.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/278)*

**Comment by KarolKaczmarek** [comment]
*[appveyor.yml, line 8 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQNERXWjlQqGwsU2uj:-KFfx45xrPnwpDjc6XxG:-1224695254) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/appveyor.yml#L8)):*
But you aren't including Tests folder in the zip anyways right? 
Regardless of whether you do or not actually, DscesourceTests contains (common tests, so it should be in the "Tests" folder, not sure why would we want to separate it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/278)*

**Comment by KarolKaczmarek** [comment]
*[Tests/xSharePoint.TestHarness.psm1, line 25 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQYqShecPSq81hztbE:-KFfzRvizWF1AzO90erV:955344725) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/Tests/xSharePoint.TestHarness.psm1#L25)):*
yup, that's it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/278)*

**Comment by BrianFarnhill** [comment]
Review status: 98 of 100 files reviewed at latest revision, 1 unresolved discussion.

---

*[appveyor.yml, line 8 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQNERXWjlQqGwsU2uj:-KFfzj06t-LGKz10IMKp:1842605944) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/appveyor.yml#L8)):*
No, in the zip file of what we ship as the module we don't include the tests at all. The thinking here is that the tests are to do with verifying the quality of what we ship - not actually part of the thing we ship if that makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/278)*

**Comment by KarolKaczmarek** [comment]
*[appveyor.yml, line 8 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQNERXWjlQqGwsU2uj:-KFg-ZiIGlPfcBuksyjS:1554550703) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/appveyor.yml#L8)):*
ok, took a look at dscresource.tests and I see what you meant. It expects module to be in the parent directory of the tests and this repo has a bit different structure than the others. 
I guess in this case we have to leave it this way. 

Also another issue is tests for all other modules are being shipped to PSGallery as well (similarily to how examples are shipped), we should probably be consistent one way or another , but that's subject of another discussion. 

as a side note - is reviewable painfully slow for you as well for PR of this size? It's almost unusable for me when using edge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/278)*

**Comment by KarolKaczmarek** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/278)*

**Comment by BrianFarnhill** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[appveyor.yml, line 8 \[r6\]](https://reviewable.io:443/reviews/powershell/xsharepoint/278#-KFQNERXWjlQqGwsU2uj:-KFg0sfS3kkr3EfnEUm4:-106121622) ([raw file](https://github.com/powershell/xsharepoint/blob/685eeba3cdfdfefa436eaa38eb7f39d005757e3a/appveyor.yml#L8)):*
OK cool, lets leave this as I've got it for now and have a wider discussion about being standard across all resources separately. 

And in terms of reviewable it's a little slow on the initial review for a lot of files, but the back and forth where it only dynamically loads the bits you are reviewing and discussing still is great. Its much faster for me to review big PRs than that standard GitHub page as that always loads everything and gets very slow. I also find that reviewable is quicker in firefox than it was for me in IE as well. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/278)*

**Pull request merged**
