### PR TITLE
Missing xSPSubscriptionSettingsProxy fix

### PR DESCRIPTION
**Pull request by camiloborges**
Adding missing proxy

### CODE REVIEW

**Comment by camiloborges** [comment]
linking it to #163

**Comment by BrianFarnhill** [comment]
@camiloborges Can I get you to drop a new line in at the end of the test file for me mate? Then I'll merge

**Comment by camiloborges** [comment]
You might be few minutes too late. Pretty sure I added the line already.  


Camilo Borges
Sent via iPhone while out and about

**Comment by BrianFarnhill** [comment]
You sure? The [Github diff](https://github.com/PowerShell/xSharePoint/pull/164/files) begs to differ, still has the little red "no new line" icon on it dude.

**Comment by camiloborges** [comment]
apparently I had either lost the change or the change was done on another
module...
anyway. should be done now

**Comment by BrianFarnhill** [comment]
Thanks bud - merging

**Pull request merged**
