### PR TITLE
xsp262 xSPIrmSettings

### PR DESCRIPTION
**Pull request by MikeLacher448**
issue 262
new resource xSPIrmSettings for management of SharePoint Irm RMS settings.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/270)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[README.md, line 118 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGxMVtv6YCj2Huke0y:-KFGxMVuGJiCLsZ0HWWa:-1354624894) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/README.md#L118)):*
Can you add this to the second line under the unreleased section where we list the other new resources we added for this release? Also looking at this I can see the content DB resoruce should be there as well - I know this wasn't you that put it in, but can I get you to fix it while you're in here?

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1, line 22 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGzB16jxsaPBsRfg8W:-KFGzB170P0zycSGmURw:-891542653) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1#L22)):*
Rather than returning null can we return a hashtable that has Ensure = "absent" in it? Then the get method will always return a hashtable that matches the schema (I know some of our other resources use this same bit of code, they are on my radar to be fixed as well, which is why I'm pulling you up on this one) 

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1, line 71 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGyWHAgOfLtx8inwL3:-KFGyWHB3wgsKWh019pP:1909788199) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1#L71)):*
Should these be $params.UseADRMS and $params.RMSserver?

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1, line 75 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGygtJl7ZmKsYBRvMh:-KFGygtJl7ZmKsYBRvMi:-165857974) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1#L75)):*
Same comment about the $params variable

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1, line 81 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGylCG_ZRRUyxypYJV:-KFGylCHwWMi2YGAQpCp:-165857974) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1#L81)):*
Same comment about the $params variable

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1, line 110 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGzQ3ZYsUyQL-u86dQ:-KFGzQ3_aONvbEHqk4ug:-641245397) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1#L110)):*
When we change the get method to not return null, we'll need to reassess this one

---

*[Tests/xSharePoint/xSharePoint.xSPIrmSettings.tests.ps1, line 37 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGziYZZiEGhCSi-S0Y:-KFGziYZZiEGhCSi-S0Z:372359230) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Tests/xSharePoint/xSharePoint.xSPIrmSettings.tests.ps1#L37)):*
After we change the get method to not return null this will need to be switched to check the ensure property

---

*[Tests/xSharePoint/xSharePoint.xSPIrmSettings.tests.ps1, line 72 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGzwKeaPxZ_JhTW4ot:-KFGzwKfsINCpZG5UlZC:1496580455) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Tests/xSharePoint/xSharePoint.xSPIrmSettings.tests.ps1#L72)):*
Can we change this to something like:

    (Get-TargetResource @testParams).Ensure | Should Be "Present"

---

*[Tests/xSharePoint/xSharePoint.xSPIrmSettings.tests.ps1, line 103 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFH-4UA5O05-dtI8KC6:-KFH-4UBvclO63h2LJQc:1496580455) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Tests/xSharePoint/xSharePoint.xSPIrmSettings.tests.ps1#L103)):*
Can we change this to something like:

    (Get-TargetResource @testParams).Ensure | Should Be "Present"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/270)*

**Comment by MikeLacher448** [comment]
No problem, I'll try to make these changes tomorrow evening (morning for you I suppose).

**Comment by MikeLacher448** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1, line 22 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGzB16jxsaPBsRfg8W:-KFeu_tXZagNoCA4d33L:974181595) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1#L22)):*
do we want to return from this? Shouldn't we Throw if the resource is run on a non farm member?

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1, line 110 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGzQ3ZYsUyQL-u86dQ:-KFeunCJasJ3tBEnnhVf:-106342399) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1#L110)):*
see my comment about throwing an error, rather than returning absent.

---

*[Tests/xSharePoint/xSharePoint.xSPIrmSettings.tests.ps1, line 37 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGziYZZiEGhCSi-S0Y:-KFevVNLLJ_G3nrToDgZ:958099587) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Tests/xSharePoint/xSharePoint.xSPIrmSettings.tests.ps1#L37)):*
again, should we throw if no farm exists?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/270)*

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1, line 22 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGzB16jxsaPBsRfg8W:-KFfPckTEVFdJaQz6ojc:1796453908) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1#L22)):*
Not for the get method, we need to return something that says what the current state is (just in terms of what the get method is really supposed to do). Now if it's not a farm member, we know that it's going to be absent and the get should indicate that. The throwing should happen on the set because then there is a blocking factor stopping it from setting correctly, but there is nothing stopping us from reporting the current state of "its not there". 

I know we aren't standard across this behavior in all resources yet but most of the newer ones line up to this and do want to bring them all in to line. An exception in the get method should represent that "I can't tell you what state it's in", and if it's not in a farm that's easy, there is no current state so we can return that. 

Does that make sense?

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1, line 110 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGzQ3ZYsUyQL-u86dQ:-KFfQKWbN4h4MrdaiRhB:1988429494) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1#L110)):*
See above response

---

*[Tests/xSharePoint/xSharePoint.xSPIrmSettings.tests.ps1, line 37 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGziYZZiEGhCSi-S0Y:-KFfQNNPsuL-vjPyElTO:1988429494) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Tests/xSharePoint/xSharePoint.xSPIrmSettings.tests.ps1#L37)):*
See above response

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/270)*

**Comment by MikeLacher448** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1, line 22 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGzB16jxsaPBsRfg8W:-KFfWbxebzRJzvRJvQmY:1166715626) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1#L22)):*
makes sense, I'll change it accordingly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/270)*

**Comment by MikeLacher448** [comment]
for some reason I cannot see what the appveyor errors are?

**Comment by BrianFarnhill** [comment]
@MikeLacher448 The branch won't merge - AppVeyor wont build something that can't be merged. You need to do a pull from the main PowerShell branch and then resolve the conflicts to be able to move forward.

    git pull https://github.com/PowerShell/xSharePoint.git dev

That will do the pull for you and it should tell you which files have conflicts (9/10 it's the readme.md file)

**Comment by MikeLacher448** [comment]
ok, I think I got it now.

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1, line 22 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGzB16jxsaPBsRfg8W:-KFg4uM9NtsJZms85aZ_:1196534626) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1#L22)):*
Quick one here, we need to include anything that is a mandatory property here. Usually I just pass through the parameters that were handed here but happy for you to include empty strings or something if you feel its more appropriate. We just need the output to match the schema.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/270)*

**Comment by MikeLacher448** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1, line 22 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/270#-KFGzB16jxsaPBsRfg8W:-KFg7iwffXdpd0AzXDjH:511866748) ([raw file](https://github.com/powershell/xsharepoint/blob/09629735c29352f227e671213c3f71f096d6cec8/Modules/xSharePoint/DSCResources/MSFT_xSPIrmSettings/MSFT_xSPIrmSettings.psm1#L22)):*
got it, fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/270)*

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/270)*

**Pull request merged**
