### PR TITLE
Add support for cloud search to xSPSearchServiceApp

### LINKED ISSUE #170: Add support for cloud search service application
xSPSearchServiceApp needs to add an option to enable to cloud search service application. This can be configured in a search service app by adding the CloudIndex option:

    New-SPEnterpriseSearchServiceApplication -Name $SearchServiceAppName -ApplicationPool $appPool -DatabaseServer $DatabaseServerName -CloudIndex $true

The change should check for the August 2015 Public Update (PU) for SharePoint Server 2013  http://support.microsoft.com/kb/3055009 before allowing that flag to be used.

### PR DESCRIPTION
**Pull request by BrianFarnhill**
Fixes #170 - Added the cloud index option to a search service app.

Code reivew: @anlynes @camiloborges @ykuijs 

- [X] Change details added to Unreleased section of readme.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [N/A] Examples updated for both the single server and small farm templates in the examples folder?

> (Not applicable as cloud search won't be a default to show off in those templates)

- [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)? 
- [X] [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) run?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/282)

### CODE REVIEW

**Comment by ykuijs** [comment]
No comments, all looks good

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/282#-:-KFhEPMZfEqjPkoxu4HU:1314564394)*

**Comment by ykuijs** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/282)*

**Comment by ykuijs** [comment]
PR has a merge conflict, which needs to be fixed

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/282)*

**Pull request merged**
