### PR TITLE
additional parameters for xSPWebAppGeneralSettings in hardened environments

### PR DESCRIPTION
**Pull request by MikeLacher448**
added the following parameters to xSPWebAppGeneralSettings
SecurityValidationExpires
SecurityValidationTimeOutMinutes
AllowOnlineWebPartCatalog
SelfServiceSiteCreationEnabled

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/261)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 112 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/261#-KErp64TQI0aW6u4xAK3:-KErp64TQI0aW6u4xAK4:-737031058) ([raw file](https://github.com/powershell/xsharepoint/blob/cfa9c1567c66955e9d332a05d917d6c1770c61fa/README.md#L112)):*
Please ping me on the steps to get the cla-required tag removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/261)*

**Comment by MikeLacher448** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 112 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/261#-KErp64TQI0aW6u4xAK3:-KEsV-pwguvROh1k9N4m:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/cfa9c1567c66955e9d332a05d917d6c1770c61fa/README.md#L112)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/261)*

**Comment by TravisEz13** [comment]
closing and reopening to update cla tag

**Comment by TravisEz13** [comment]
Reviewed 1 of 5 files at r2.
Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/261)*

**Comment by BrianFarnhill** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/xSharePoint/xSharePoint.xSPWebAppGeneralSettings.Tests.ps1, line 13 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/261#-KEzu6cIeu1PFiQRz-6l:-KEzu6cJIbOLD7vqUiEQ:-412872655) ([raw file](https://github.com/powershell/xsharepoint/blob/cfa9c1567c66955e9d332a05d917d6c1770c61fa/Tests/xSharePoint/xSharePoint.xSPWebAppGeneralSettings.Tests.ps1#L13)):*
Why do we need to force the import of the module here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/261)*

**Comment by MikeLacher448** [comment]
the -force is left over from testing. Changes to the code would not reload in the same powershell session. I'll remove and re-commit.

**Comment by MikeLacher448** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/xSharePoint/xSharePoint.xSPWebAppGeneralSettings.Tests.ps1, line 13 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/261#-KEzu6cIeu1PFiQRz-6l:-KF0SSBiPeGTornO6RUv:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/cfa9c1567c66955e9d332a05d917d6c1770c61fa/Tests/xSharePoint/xSharePoint.xSPWebAppGeneralSettings.Tests.ps1#L13)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/261)*

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/261)*

**Pull request merged**
