### PR TITLE
issue #243: support for offline feature installation

### PR DESCRIPTION
**Pull request by MikeLacher448**
added SXSpath parameter to xSPInstallPrereqs to support installation of prerequisite windows features in offline environments.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/259)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPInstallPrereqs/MSFT_xSPInstallPrereqs.schema.mof, line 8 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/259#-KEhkK9NA_7HNOWx_4Bf:-KEhkK9OgXqYQD9-YeXD:-1903898402) ([raw file](https://github.com/powershell/xsharepoint/blob/ee0735e4377b8a60793692e4c2066201300ef561/Modules/xSharePoint/DSCResources/MSFT_xSPInstallPrereqs/MSFT_xSPInstallPrereqs.schema.mof#L8)):*
We try to stick to some GitHub MarkDown sysntax on these, can you make sure we start new sentences on a new line here? It'll get handled when we generate the doco from this

---

*[Tests/xSharePoint/xSharePoint.xSPInstallPrereqs.Tests.ps1, line 313 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/259#-KEhkhBRFll6v2o6rOdH:-KEhkhBSPc3k5vSf4UJw:1027233170) ([raw file](https://github.com/powershell/xsharepoint/blob/ee0735e4377b8a60793692e4c2066201300ef561/Tests/xSharePoint/xSharePoint.xSPInstallPrereqs.Tests.ps1#L313)):*
Looks like there is no empty line to finish the file, can you just drop a line break on this for me?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/259)*

**Comment by MikeLacher448** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/xSharePoint/xSharePoint.xSPInstallPrereqs.Tests.ps1, line 313 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/259#-KEhkhBRFll6v2o6rOdH:-KEi2PqAtukP5XoDuHX9:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/ee0735e4377b8a60793692e4c2066201300ef561/Tests/xSharePoint/xSharePoint.xSPInstallPrereqs.Tests.ps1#L313)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/259)*

**Comment by MikeLacher448** [comment]
added the CR at the end of the test, and fixed my additional text in the MOF.

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/259)*

**Pull request merged**
