### PR TITLE
Added Reverse DSC Module

### PR DESCRIPTION
**Pull request by NikCharlebois**
The Reverse DSC module is a script that allows a user to automatically generate the DSC configuration script for a given SharePoint farm (using xSharePoint).

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Hey dude, this one is gonna take some time to get across and do a detailed review on. Leave it with me and expect me to ping you directly to discuss some of this. Just wanted to put something here to make sure you knew I was looking at it and not ignoring the PR.

**Comment by kilasuit** [comment]
@BrianFarnhill - I'm planning to do a DSC build and then a reverse DSC Build when I get the chance to (hopefully this weekend)

**Comment by ykuijs** [comment]
This is a killer feature!! Will try to do some testing as well if I can find some time!

**Comment by camiloborges** [comment]
@nikcharlebois this an amazona addition to this project.

We should definitely get this thing added.

It doesn't cover all modules yet does it? We'll probably need some smarts for things like spwebapp.blocked and allowed files, as well as ups property and section

**Comment by BrianFarnhill** [comment]
@camiloborges @ykuijs @NikCharlebois I've been discussing this with @caadam this week and we have a bunch of ideas on how to refine this and better incorporate it, will email you all separately this week with that discussion. Definitely wanna get this in there, but just wanna make sure we are mindful of a few things in the approach :)

**Pull request closed without merging**
