### PR TITLE
Updating issue and PR templates

### PR DESCRIPTION
**Pull request by KarolKaczmarek**
Sending changes related to my feedback to PR: https://reviewable.io/reviews/powershell/xsharepoint/264
(see code comments section) 

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/272)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 8 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/272#-KF6gNbeYNSBrVdhmWL_:-KF6gNbeYNSBrVdhmWLa:-429893246) ([raw file](https://github.com/powershell/xsharepoint/blob/fafb71ea0841663ebb8a3bfd9f6d952624df6af5/.github/PULL_REQUEST_TEMPLATE.md#L8)):*
How are the other DSC resources capturing documentation for changes that come through like new resources? We took this approach to make sure we got the documentation as part of the pull request rather than something that we have to keep up to date separately. I'm happy to remove this if we have another way of doing the documentation, but otherwise this is something that we do make sure every single PR has before we let it in so we keep our documentation up to date.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/272)*

**Comment by KarolKaczmarek** [comment]
*[.github/PULL_REQUEST_TEMPLATE.md, line 8 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/272#-KF6gNbeYNSBrVdhmWL_:-KF6wDD0FphLoXV2qpYJ:-878127415) ([raw file](https://github.com/powershell/xsharepoint/blob/fafb71ea0841663ebb8a3bfd9f6d952624df6af5/.github/PULL_REQUEST_TEMPLATE.md#L8)):*
Agree regarding the documentation, that's important and something we will want for every PR. I somehow got focused on updating schema.mof which really doesn't change/needs to be updated that often so I don't think it should be part of the template.
How about we change this section to:
[  ] Added/updated documentation to reflect your changes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/272)*

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 8 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/272#-KF6gNbeYNSBrVdhmWL_:-KF6xGEIcXsYwuPC6GQO:-1647143028) ([raw file](https://github.com/powershell/xsharepoint/blob/fafb71ea0841663ebb8a3bfd9f6d952624df6af5/.github/PULL_REQUEST_TEMPLATE.md#L8)):*
Happy with that approach

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/272)*

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xsharepoint/272#-KFCp2jgnPDBS8oIl_R3:-KFCp2jgnPDBS8oIl_R4:1541809457) (no related file):*
Just need you to do a pull from PowerShell/dev so this can be merged after we made other changes to the issue template.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/272)*

**Comment by KarolKaczmarek** [comment]
Closing this since we've modified the issue template with https://github.com/PowerShell/xSharePoint/pull/276

**Pull request closed without merging**
