### PR TITLE
Added Cloud Index

### PR DESCRIPTION
**Pull request by NikCharlebois**
Added new parameter for Cloud Search service Application

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/228)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
@NikCharlebois I need you to have a look at whats happened in the unit tests with this one dude, then we can review it in full

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPSearchServiceApp/MSFT_xSPSearchServiceApp.psm1, line 51 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/228#-KE4mpBIOjYltBrXYzzO:-KE4mpBJIdAHzztE3Il0:-1618683180) ([raw file](https://github.com/powershell/xsharepoint/blob/82179c6f3f8b13e85aa4b876ed264c222f1a4d67/Modules/xSharePoint/DSCResources/MSFT_xSPSearchServiceApp/MSFT_xSPSearchServiceApp.psm1#L51)):*
Can we add an else statement to this if statement that returns the value as false if the version isn't high enough? Also can we add a line to store the output from Get-xSharePointInstalledProductVersion so we don't call it twice?

    $version = Get-xSharePointInstalledProductVersion
    if ($version.FileMajorPart -ge15 -and $version.FileBuildPart -ge 4745)

Lastly we need to consider the logic here. Right now version 16.0.4700 (as an example number) would fail because the build part isn't high enough. So we need to say "if your version is 16 or higher, or the version is 15 and the build is higher than 4745"

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPSearchServiceApp/MSFT_xSPSearchServiceApp.psm1, line 86 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/228#-KE4mytFrUKxn3lm7GhG:-KE4mytFrUKxn3lm7GhH:-1491703118) ([raw file](https://github.com/powershell/xsharepoint/blob/82179c6f3f8b13e85aa4b876ed264c222f1a4d67/Modules/xSharePoint/DSCResources/MSFT_xSPSearchServiceApp/MSFT_xSPSearchServiceApp.psm1#L86)):*
Can we throw an else on the other end of this  that will throw an error saying you can't specify cloud index for a version that low? Same remarks as above for the logic and pulling the Get call there to one line.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/powershell/xsharepoint/228)*

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xsharepoint/228#-KE4nrhXJHoZFIlbI6k0:-KE4nrhYM8bV63cRaWi3:243970668) (no related file):*
I also need you to update readme.md with what you changed added to the list under the "unreleased" section

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/powershell/xsharepoint/228)*

**Comment by BrianFarnhill** [comment]
@NikCharlebois Are you still looking at this one mate? Has been almost 2 weeks with no movement. I'm happy to pick this up to finish it off if you need the help, just let me know.

**Comment by NikCharlebois** [comment]
Hey Brian,

Yes, I'll try to wrap it up over the next day or two. Sorry for the delays!

**Comment by BrianFarnhill** [comment]
@NikCharlebois I took a swing at this last night - I'm totally done except for the fact that I need to update the build number of the mocks we test against for the unit tests, so if you want to park this I can bring it home in my branch if that is easier?

**Comment by BrianFarnhill** [comment]
Closing as inactive - replacement has been finalised in #282

**Pull request closed without merging**
