### PR TITLE
New xSPQuotaTemplate and xSPDesignerSettings resource

### PR DESCRIPTION
**Pull request by ykuijs**
This PR adds the xSPQuotaTemplate resource, according to #91

As requested: I have used the VS project and created a test file. Since I am not sure how to use and test the Tests file, I tried to edit it as good as possible. Please let me know if anything should be changed.

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Just noting here that @ykuijs and I are having an offline discussion about how the tests in this one should be approached so that we can merge it in and test it.

**Comment by ykuijs** [comment]
Somehow I managed to include the xSPDesignerSettings into this branch, even though I created a separate branch for it. So the resource for issue #23 is also in this PR.

Still learning to use Git :-p

**Comment by BrianFarnhill** [comment]
@ykuijs I've done a merge and touch up of this one that is ready to merge in and sent you a [pull request with the changes](https://github.com/ykuijs/xSharePoint/pull/2). Once you accept that merge the changes will turn up here and we can commit these to the dev branch

**Comment by ykuijs** [comment]
@BrianFarnhill - Merge has been completed! Go ahead and commit these changes to your dev branch.

**Pull request merged**
