### PR TITLE
Remove experimental status

### PR DESCRIPTION
**Pull request by BrianFarnhill**
Code review for @KarolKaczmarek on this one (tagging @vors and @TravisEz13 in case they want to look at it as well).

As discussed, this is the change to rename from xSharePoint to SharePointDSC, and will be the last change we bring in to make this version 1.0. Ping me via email for further discussion guys.

- [X] Change details added to Unreleased section of readme.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/286)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
This is on hold for some internal discussion - leaving the PR open as we are close though

**Comment by camiloborges** [comment]
Fingers crossed

**Comment by BrianFarnhill** [comment]
Looks like the tests are failing because of a known issue that was introduced yesterday to DscResource.Tests - details at https://github.com/PowerShell/DscResource.Tests/issues/46

**Comment by BrianFarnhill** [comment]
The changes we need are in a PR at https://github.com/PowerShell/DscResource.Tests/pull/47 - when this goes through we can re-run the tests here to see a green light

**Comment by BrianFarnhill** [comment]
Reviewed 401 of 409 files at r1, 16 of 20 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/286)*

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 409 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/286)*

**Comment by camiloborges** [comment]
yay!

**Pull request merged**
