### PR TITLE
Add xSPContentDatabase resource

### PR DESCRIPTION
**Pull request by ykuijs**
New xSPContentDatabase like mentioned in issue #201 

Please review and let me know any comments!

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/241)

### CODE REVIEW

**Comment by ykuijs** [comment]
Crap, one small change broke some of my tests.....will update these and do another commit.

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 13 unresolved discussions.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.psm1, line 40 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4ergxgQd-TGFVM9Di:-KE4ergypu9oKX_c2biP:-114126020) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.psm1#L40)):*
It looks like you are just trying to trim the "/" off the end of the URL here - you can do this with $cdb.WebApplication.Url.Trim('/') - if there is a / it will be removed from the start and end of the string, if not the string is returned as is.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.psm1, line 100 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4fSFtPE_3b9_RpQx4:-KE4fSFtPE_3b9_RpQx5:242565465) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.psm1#L100)):*
Again look to use the Trim() method here as mentioned above.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.psm1, line 160 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4fx5eUy-F58EJU4fr:-KE4fx5f62YHttqmnpZi:-592924718) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.psm1#L160)):*
Rather than have this throw, I'm inclined to let the test method log it and still return false - because that's indicative of it not being in a supported state, and the set method can throw the hard exception. What do you think?

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.schema.mof, line 6 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4gM7IY9NBrExN3B-l:-KE4gM7KXXLZFlxdsAkW:1181478983) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.schema.mof#L6)):*
Can you combine the Note: with the line after it to be on the one line?

    Note: The resource cannot be used to move the database to a different SQL instance.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.schema.mof, line 14 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4gcEGGxPduZodHDBJ:-KE4gcEHkCt2URZJHcfh:-1462779411) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.schema.mof#L14)):*
Should the comment on this line still be there?

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.schema.mof, line 32 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4gpE4coWYLqW1PKFm:-KE4gpE57y-gBX6Qgeep:1403216244) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.schema.mof#L32)):*
I think this description came from another resource, can you please review it for this one (the word template threw me)

---

*[Modules/xSharePoint/Modules/xSharePoint.ContentDatabase/xSPContentDatabase.psm1, line 1 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4h1jxmdUyvfa7X6Ub:-KE4h1jxmdUyvfa7X6Uc:1122012579) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Modules/xSharePoint/Modules/xSharePoint.ContentDatabase/xSPContentDatabase.psm1#L1)):*
Why is this in it's own file? Shouldn't it be able to run as part of the main module?

---

*[Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1, line 59 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4hNyo2HyCFGxuloVc:-KE4hNyo2HyCFGxuloVd:1992518849) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1#L59)):*
Rather than just test for not null or empty, can we test the ensure property as a way to know if it found the DB or not in what is returned here?

    (Get-TargetResource @testParams).Ensure | Should Be "Present"

---

*[Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1, line 86 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4haqulb_Lko-QMJYK:-KE4haqvl_nMZs1r1cQ-:382245592) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1#L86)):*
Same comment about testing ensure as above

---

*[Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1, line 135 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4hm-erkIpq9fLoucS:-KE4hm-erkIpq9fLoucT:382245592) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1#L135)):*
Same comment about testing ensure as above

---

*[Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1, line 166 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4hppGyLy4xEiUY0uE:-KE4hppH7pS_ALsyzuxK:382245592) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1#L166)):*
Same comment about testing ensure as above

---

*[Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1, line 200 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4htF6QOf9muuJfaI6:-KE4htF6QOf9muuJfaI7:382245592) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1#L200)):*
Same comment about testing ensure as above

---

*[Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1, line 244 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4hvW11iy7lAijRbem:-KE4hvW2bal9y-1Zubgj:382245592) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1#L244)):*
Same comment about testing ensure as above

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/powershell/xsharepoint/241)*

**Comment by BrianFarnhill** [comment]
Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/powershell/xsharepoint/241)*

**Comment by ykuijs** [comment]
Review status: 0 of 4 files reviewed at latest revision, 13 unresolved discussions.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.psm1, line 40 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4ergxgQd-TGFVM9Di:-KE6_fc7OtIUonx4W6yh:-82894076) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.psm1#L40)):*
Corrected

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.psm1, line 100 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4fSFtPE_3b9_RpQx4:-KE6akDCeWHRC68obtNP:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.psm1#L100)):*
Done.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.psm1, line 160 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4fx5eUy-F58EJU4fr:-KE6angkBAPBA9-Q8Ob4:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.psm1#L160)):*
Done.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.schema.mof, line 6 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4gM7IY9NBrExN3B-l:-KE6apVtUup7CYwDjkBE:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.schema.mof#L6)):*
Done.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.schema.mof, line 14 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4gcEGGxPduZodHDBJ:-KE6atSCyDHexa-cCkEX:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.schema.mof#L14)):*
Done.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.schema.mof, line 32 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4gpE4coWYLqW1PKFm:-KE6asJmB8C0jHkBrIPG:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Modules/xSharePoint/DSCResources/MSFT_xSPContentDatabase/MSFT_xSPContentDatabase.schema.mof#L32)):*
Done.

---

*[Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1, line 59 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4hNyo2HyCFGxuloVc:-KE6avFbsaXuWzMRO7yN:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1#L59)):*
Done.

---

*[Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1, line 86 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4haqulb_Lko-QMJYK:-KE6awS4sIeWI2o0TReS:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1#L86)):*
Done.

---

*[Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1, line 135 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4hm-erkIpq9fLoucS:-KE6axbdHW0EntoaxWbc:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1#L135)):*
Done.

---

*[Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1, line 166 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4hppGyLy4xEiUY0uE:-KE6az-26CO0mNAQ4Jxd:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1#L166)):*
Done.

---

*[Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1, line 200 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4htF6QOf9muuJfaI6:-KE6b-CpxgBqj8vzQz8O:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1#L200)):*
Done.

---

*[Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1, line 244 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4hvW11iy7lAijRbem:-KE6b0OkmRUWHB3npcl-:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Tests/xSharePoint/xSharePoint.xSPContentDatabase.Tests.ps1#L244)):*
Done.

---

*[Modules/xSharePoint/Modules/xSharePoint.ContentDatabase/xSPContentDatabase.psm1, line 1 \[r2\]](https://reviewable.io:443/reviews/powershell/xsharepoint/241#-KE4h1jxmdUyvfa7X6Ub:-KE6b2EoHqEG0xCiX7tx:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/5f32ef276b6752b7bee362872b7d4a7aeb6e9115/Modules/xSharePoint/Modules/xSharePoint.ContentDatabase/xSPContentDatabase.psm1#L1)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/powershell/xsharepoint/241)*

**Comment by BrianFarnhill** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/powershell/xsharepoint/241)*

**Pull request merged**
