### PR TITLE
Bug fix for claims accounts in cache values

### PR DESCRIPTION
**Pull request by BrianFarnhill**
@camiloborges @ykuijs @caadam  @anlynes - Code review. Found a minor bug working with Andrew on the cache accounts when the property bag values aren't set in claims format.

- [X] Change details added to Unreleased section of readme.md?
- [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/288)

### CODE REVIEW

**Comment by ykuijs** [comment]
One small markup issue. The rest looks good.

<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> #### Bug fix for claims accounts in cache values
> 
> @camiloborges @ykuijs @caadam  @anlynes - Code review. Found a minor bug working with Andrew on the cache accounts when the property bag values aren't set in claims format.
> 
> 
> 
> - [X] Change details added to Unreleased section of readme.md?
> 
> - [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
> 
> - [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?
> 
> 
> </details>


---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPCacheAccounts/MSFT_xSPCacheAccounts.psm1, line 60 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/288#-KHLmGCMTjnbRV-DtACL:-KHLmGCN3_4_BJNhxEHr:-399305341) ([raw file](https://github.com/powershell/xsharepoint/blob/8a58532c35f36816ddb2dba9d24df2741130f878/Modules/xSharePoint/DSCResources/MSFT_xSPCacheAccounts/MSFT_xSPCacheAccounts.psm1#L60)):*
> ```PowerShell
>         } else {
>             if ($wa.Properties.ContainsKey("portalsuperuseraccount")) { 
>             $returnVal.Add("SuperUserAlias", $wa.Properties["portalsuperuseraccount"])
> ```

Incorrect identation, missing a tab

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/288#-:-KHLmguRGGK-3JcY8D2U:-1396625933)*

**Comment by BrianFarnhill** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/xSharePoint/DSCResources/MSFT_xSPCacheAccounts/MSFT_xSPCacheAccounts.psm1, line 60 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/288#-KHLmGCMTjnbRV-DtACL:-KHMsOWNssAFE-HiGfeY:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/8a58532c35f36816ddb2dba9d24df2741130f878/Modules/xSharePoint/DSCResources/MSFT_xSPCacheAccounts/MSFT_xSPCacheAccounts.psm1#L60)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary>
> Incorrect identation, missing a tab</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/288)*

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/288)*

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/288)*

**Pull request merged**
